name: Lee-Brown
favicon: null
layout_spectrum: 0.8358686547726393
typography_spectrum: 0.6155726066790521
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.9582842600066215
  lightness: 0.0022921606432646513
  saturation: 0.5310478643514216
  rhythmicContrast: 0.5865142296534032
purpose: []
