name: Lee-Brown
favicon: null
layout_spectrum: 1
typography_spectrum: 0.33817
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#85331b'
    - '#f3803f'
    - '#b3a78d'
    - '#6f5f46'
  brandStrength: 1
  lightness: 0.6875
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
